create table contenido (
  id bigint generated by default as identity primary key,
  tema text not null,
  titulo text not null,
  texto text not null,
  generado_en timestamp with time zone default now()
);
